<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="quarto-1.10.18" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />

<meta name="dcterms.date" content="2026-09-04" />

<title>Tetracyclines and the risk of Clostridioides difficile infection – Tetracyclines & C. difficile</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<!-- htmldependencies:E3FAD763 -->
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  
  <script>
    (function () {
      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src  = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js";
      document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>


<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="/index.html">
    <span class="navbar-title">Tetracyclines &amp; C. difficile</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
  aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation"
  onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="/index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/report.html"> 
<span class="menu-text">Meta-analysis report</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tetracyclines and the risk of <em>Clostridioides difficile</em> infection</h1>
<p class="subtitle lead">Updated systematic review &amp; Bayesian random-effects meta-analysis</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 4, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<style>
  body.lang-en .it { display: none; }
  body.lang-it .en { display: none; }
  .lang-toggle { display:flex; gap:0; border:1px solid #2c7fb8; border-radius:999px;
    overflow:hidden; width:max-content; margin:0 0 1.5rem; }
  .lang-toggle button { background:#fff; color:#2c7fb8; border:0; padding:.45rem 1rem;
    cursor:pointer; font-size:.9rem; font-weight:600; }
  .lang-toggle button.active { background:#2c7fb8; color:#fff; }
  .card { background:#f2f7fb; border:1px solid #d4e3ef; border-radius:12px;
    padding:1rem 1.25rem; margin:1rem 0; }
  .big { font-size:1.6rem; font-weight:700; color:#2c7fb8; }
  .cap { color:#5a6b7a; font-size:.88rem; margin:.3rem 0 1.4rem; }
</style>
<div class="lang-toggle" role="group" aria-label="Language">
<p><button id="btn-en" class="active" onclick="setLang('en')">English</button> <button id="btn-it" onclick="setLang('it')">Italiano</button></p>
</div>
<script>
  function setLang(l){
    document.body.classList.remove("lang-en","lang-it");
    document.body.classList.add("lang-"+l);
    document.documentElement.lang = l;
    document.getElementById("btn-en").classList.toggle("active", l==="en");
    document.getElementById("btn-it").classList.toggle("active", l==="it");
  }
  document.addEventListener("DOMContentLoaded", function(){ setLang("en"); });
</script>
<section id="research-questiondomanda-di-ricerca" class="level2">
<h2><span class="en">Research question</span><span class="it">Domanda di ricerca</span></h2>
<div class="en">
<p>Among patients exposed to systemic antibiotics, is exposure to a tetracycline-class antibiotic associated with a different risk of incident <em>C. difficile</em> infection (CDI) <strong>compared with other antibiotics</strong>? This report re-estimates the association within a Bayesian random-effects framework and quantifies the posterior probability of a protective effect. Studies whose only comparator was “no antibiotic” are analysed separately as a secondary comparison, per the PROSPERO protocol’s PECO.</p>
</div>
<div class="it">
<p>Nei pazienti esposti ad antibiotici sistemici, l’esposizione a un antibiotico della classe delle tetracicline è associata a un rischio diverso di infezione incidente da <em>C. difficile</em> (ICD) <strong>rispetto ad altri antibiotici</strong>? Questo report ristima l’associazione con un modello bayesiano a effetti casuali e quantifica la probabilità a posteriori di un effetto protettivo. Gli studi il cui unico comparatore era “nessun antibiotico” sono analizzati separatamente come confronto secondario, secondo il PECO del protocollo PROSPERO.</p>
</div>
</section>
<section id="study-selection-prisma-2020selezione-degli-studi-prisma-2020" class="level2">
<h2><span class="en">Study selection (PRISMA 2020)</span><span class="it">Selezione degli studi (PRISMA 2020)</span></h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img src="report_figs/prisma2020_flow.png" class="img-fluid quarto-figure quarto-figure-center" style="width:100.0%" /></p>
</figure>
</div>
<div class="cap">
<div class="en">
<p><strong>PRISMA 2020 flow.</strong> Canonical PRISMA 2020 diagram (generated with the <code>PRISMA2020</code> R package). Identification and de-duplication counts are validated (2,926 database + 1 register records + 95 from citation searching of Tariq 2018; 1,452 duplicates removed). Screening-stage counts are <em>provisional</em>, reconstructed from the Elicit AI second-screen pending human dual screening per the protocol (<code>PRISMA_flow_data.xlsx</code>): databases/registers arm 1,475 screened → 40 assessed → 11 full-text exclusions; the 95 other-methods (citation) reports yielded no additional eligible study. Of the 35 included studies (29 new + 6 carried forward from Tariq 2018), 20 contribute a curated effect size to the Bayesian meta-analysis: <strong>11 in the primary comparison</strong> (tetracyclines vs other antibiotics) and <strong>9 in the secondary comparison</strong> (tetracyclines vs no antibiotic).</p>
</div>
<div class="it">
<p><strong>Flusso PRISMA 2020.</strong> Diagramma PRISMA 2020 canonico (generato con il pacchetto R <code>PRISMA2020</code>). I conteggi di identificazione e deduplicazione sono validati (2.926 record da database + 1 registro + 95 da citation searching di Tariq 2018; 1.452 duplicati rimossi). I conteggi della fase di screening sono <em>provvisori</em>, ricostruiti dal secondo screening AI di Elicit in attesa del doppio screening manuale secondo il protocollo (<code>PRISMA_flow_data.xlsx</code>): braccio database/registri 1.475 sottoposti a screening → 40 valutati → 11 esclusioni full-text; i 95 report da altri metodi (citation searching) non hanno prodotto ulteriori studi eleggibili. Dei 35 studi inclusi (29 nuovi + 6 trasferiti da Tariq 2018), 20 contribuiscono con una stima curata alla meta-analisi bayesiana: <strong>11 nel confronto primario</strong> (tetracicline vs altri antibiotici) e <strong>9 nel confronto secondario</strong> (tetracicline vs nessun antibiotico).</p>
</div>
</div>
</section>
<section id="table-1.-characteristics-of-included-studiestabella-1.-caratteristiche-degli-studi-inclusi" class="level2">
<h2><span class="en">Table 1. Characteristics of included studies</span><span class="it">Tabella 1. Caratteristiche degli studi inclusi</span></h2>
<table class="caption-top">
<colgroup>
<col style="width: 14%" />
<col style="width: 17%" />
<col style="width: 6%" />
<col style="width: 9%" />
<col style="width: 15%" />
<col style="width: 16%" />
<col style="width: 4%" />
<col style="width: 14%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Study</th>
<th style="text-align: left;">Design</th>
<th style="text-align: left;">Setting</th>
<th style="text-align: right;">N</th>
<th style="text-align: left;">Agent</th>
<th style="text-align: left;">Comparator</th>
<th style="text-align: center;">Adj.</th>
<th style="text-align: right;">OR (95% CI)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Watson2018">(<a href="#ref-Watson2018" role="doc-biblioref">Watson et al. 2018</a>)</span></td>
<td style="text-align: left;">retrospective cohort</td>
<td style="text-align: left;">HA</td>
<td style="text-align: right;">1,237,537</td>
<td style="text-align: left;">tetracycline class</td>
<td style="text-align: left;">reference category</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">0.39 (0.31-0.51)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Baxter2008">(<a href="#ref-Baxter2008" role="doc-biblioref">Baxter et al. 2008</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">HA</td>
<td style="text-align: right;">4,493</td>
<td style="text-align: left;">doxycycline</td>
<td style="text-align: left;">reference category</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">0.41 (0.27-0.63)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Strom2017">(<a href="#ref-Strom2017" role="doc-biblioref">Ström et al. 2017</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">mixed</td>
<td style="text-align: right;">584</td>
<td style="text-align: left;">tetracycline</td>
<td style="text-align: left;">no antibiotic</td>
<td style="text-align: center;">No</td>
<td style="text-align: right;">0.60 (0.14-2.55)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Webb2020">(<a href="#ref-Webb2020" role="doc-biblioref">Webb et al. 2020</a>)</span></td>
<td style="text-align: left;">retrospective cohort</td>
<td style="text-align: left;">HA</td>
<td style="text-align: right;">506,068</td>
<td style="text-align: left;">doxycycline</td>
<td style="text-align: left;">reference category</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">0.60 (0.33-1.10)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Doernberg2012">(<a href="#ref-Doernberg2012" role="doc-biblioref">Doernberg et al. 2012</a>)</span></td>
<td style="text-align: left;">retrospective cohort</td>
<td style="text-align: left;">mixed</td>
<td style="text-align: right;">2,734</td>
<td style="text-align: left;">doxycycline</td>
<td style="text-align: left;">specific comparator</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">0.73 (0.56-0.96)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Tilton2019">(<a href="#ref-Tilton2019" role="doc-biblioref">Tilton and Johnson 2019</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">HA</td>
<td style="text-align: right;">200</td>
<td style="text-align: left;">doxycycline</td>
<td style="text-align: left;">no antibiotic</td>
<td style="text-align: center;">No</td>
<td style="text-align: right;">0.76 (0.27-2.13)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="OLeary2023">(<a href="#ref-OLeary2023" role="doc-biblioref">O’Leary et al. 2023</a>)</span></td>
<td style="text-align: left;">retrospective cohort</td>
<td style="text-align: left;">HA</td>
<td style="text-align: right;">156,107</td>
<td style="text-align: left;">doxycycline</td>
<td style="text-align: left;">specific comparator</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">0.83 (0.70-0.99)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Tartof2015">(<a href="#ref-Tartof2015" role="doc-biblioref">Tartof et al. 2015</a>)</span></td>
<td style="text-align: left;">retrospective cohort</td>
<td style="text-align: left;">HA</td>
<td style="text-align: right;">401,234</td>
<td style="text-align: left;">tetracycline class</td>
<td style="text-align: left;">no antibiotic</td>
<td style="text-align: center;">No</td>
<td style="text-align: right;">0.84 (0.63-1.10)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Delaney2007">(<a href="#ref-Delaney2007" role="doc-biblioref">Delaney et al. 2007</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">CA</td>
<td style="text-align: right;">13,563</td>
<td style="text-align: left;">tetracycline class</td>
<td style="text-align: left;">no antibiotic</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">0.90 (0.52-1.56)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Boven2026">(<a href="#ref-Boven2026" role="doc-biblioref">Boven et al. 2026</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">mixed</td>
<td style="text-align: right;">398,080</td>
<td style="text-align: left;">tetracycline class</td>
<td style="text-align: left;">reference category</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">0.93 (0.80-1.09)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Carmichael2023">(<a href="#ref-Carmichael2023" role="doc-biblioref">Carmichael et al. 2023</a>)</span></td>
<td style="text-align: left;">retrospective cohort</td>
<td style="text-align: left;">mixed</td>
<td style="text-align: right;">50,861,011</td>
<td style="text-align: left;">doxycycline</td>
<td style="text-align: left;">reference category</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">0.94 (0.89-0.99)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Kuntz2011">(<a href="#ref-Kuntz2011" role="doc-biblioref">Kuntz et al. 2011</a>)</span></td>
<td style="text-align: left;">nested case control</td>
<td style="text-align: left;">CA</td>
<td style="text-align: right;">3,344</td>
<td style="text-align: left;">tetracycline class</td>
<td style="text-align: left;">reference category</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">0.94 (0.43-2.05)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Miller2023">(<a href="#ref-Miller2023" role="doc-biblioref">Miller et al. 2023</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">CA</td>
<td style="text-align: right;">956,424</td>
<td style="text-align: left;">doxycycline</td>
<td style="text-align: left;">reference category</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">0.96 (0.90-1.03)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Guh2015">(<a href="#ref-Guh2015" role="doc-biblioref">Guh et al. 2017</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">CA</td>
<td style="text-align: right;">452</td>
<td style="text-align: left;">tetracycline</td>
<td style="text-align: left;">no antibiotic</td>
<td style="text-align: center;">No</td>
<td style="text-align: right;">1.00 (0.23-4.35)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Dial2008">(<a href="#ref-Dial2008" role="doc-biblioref">Dial et al. 2008</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">CA</td>
<td style="text-align: right;">NR</td>
<td style="text-align: left;">tetracycline class</td>
<td style="text-align: left;">no antibiotic</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">1.10 (0.12-10.20)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Adams2017">(<a href="#ref-Adams2017" role="doc-biblioref">Adams et al. 2017</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">CA</td>
<td style="text-align: right;">5,324</td>
<td style="text-align: left;">tetracycline class</td>
<td style="text-align: left;">reference category</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">1.26 (0.46-3.45)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Brown2016">(<a href="#ref-Brown2016" role="doc-biblioref">Brown et al. 2016</a>)</span></td>
<td style="text-align: left;">nested case control</td>
<td style="text-align: left;">HA</td>
<td style="text-align: right;">169,453</td>
<td style="text-align: left;">tetracycline</td>
<td style="text-align: left;">no antibiotic</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">1.26 (0.86-1.85)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Predrag2016">(<a href="#ref-Predrag2016" role="doc-biblioref">Stojanović 2016</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">HA</td>
<td style="text-align: right;">111</td>
<td style="text-align: left;">tetracycline class</td>
<td style="text-align: left;">no antibiotic</td>
<td style="text-align: center;">No</td>
<td style="text-align: right;">1.35 (0.22-8.47)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Yu2021">(<a href="#ref-Yu2021" role="doc-biblioref">Yu et al. 2021</a>)</span></td>
<td style="text-align: left;">matched case control</td>
<td style="text-align: left;">HA</td>
<td style="text-align: right;">1,443</td>
<td style="text-align: left;">tetracycline</td>
<td style="text-align: left;">no antibiotic</td>
<td style="text-align: center;">No</td>
<td style="text-align: right;">2.90 (1.33-6.33)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Saito2025">(<a href="#ref-Saito2025" role="doc-biblioref">Saito et al. 2025</a>)</span></td>
<td style="text-align: left;">nested case control</td>
<td style="text-align: left;">mixed</td>
<td style="text-align: right;">24,585</td>
<td style="text-align: left;">tetracycline class</td>
<td style="text-align: left;">reference category</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">2.97 (2.44-3.62)</td>
</tr>
</tbody>
</table>
<div class="cap">
<div class="en">
<p><strong>Table 1.</strong> Characteristics of the 20 studies contributing to the Bayesian synthesis (11 vs other antibiotics; 9 vs no antibiotic; ordered by odds ratio). N = analytic sample size (NR = not reported); Adj. = adjusted estimate. The OR is the single curated effect size carried into the meta-analysis; each study is identified by its bibliographic citation.</p>
</div>
<div class="it">
<p><strong>Tabella 1.</strong> Caratteristiche dei 20 studi nella sintesi bayesiana (11 vs altri antibiotici; 9 vs nessun antibiotico; ordinati per odds ratio). N = dimensione campionaria analitica (NR = non riportata); Adj. = stima aggiustata. L’OR è la singola stima d’effetto curata usata nella meta-analisi; ogni studio è identificato dalla relativa citazione bibliografica.</p>
</div>
</div>
</section>
<section id="risk-of-bias-newcastle-ottawa-scalerischio-di-bias-scala-newcastle-ottawa" class="level2">
<h2><span class="en">Risk of bias (Newcastle-Ottawa Scale)</span><span class="it">Rischio di bias (scala Newcastle-Ottawa)</span></h2>
<div class="en">
<p>All 20 studies contributing to the synthesis are observational, so risk of bias was assessed with the Newcastle-Ottawa Scale (NOS) <span class="citation" data-cites="WellsNOS">(<a href="#ref-WellsNOS" role="doc-biblioref">Wells et al. 2011</a>)</span>, using the design-appropriate version (cohort or case-control; maximum 9 stars across the Selection, Comparability and Outcome/Exposure domains). Uniform decision rules were applied: the case-definition item was credited only for laboratory-confirmed or independently validated definitions (unvalidated ICD/claims algorithms were not); comparability stars required matching or adjustment for age/sex (first star) and for additional key confounders (second star), so studies whose curated estimate is unadjusted beyond matching received one comparability star; for cohorts, completeness of follow-up was credited only for closed healthcare systems (HMO, claims or population registers). Overall ratings: 7-9 stars = <strong>low</strong> risk of bias, 5-6 = <strong>some concerns</strong>, 4 or fewer = <strong>high</strong>. Per-item scores and study-level justifications are recorded in <code>nos_assessment.csv</code>.</p>
</div>
<div class="it">
<p>Tutti i 20 studi che contribuiscono alla sintesi sono osservazionali; il rischio di bias è stato valutato con la scala Newcastle-Ottawa (NOS) <span class="citation" data-cites="WellsNOS">(<a href="#ref-WellsNOS" role="doc-biblioref">Wells et al. 2011</a>)</span>, nella versione appropriata al disegno (coorte o caso-controllo; massimo 9 stelle nei domini Selezione, Comparabilità ed Esito/Esposizione). Sono state applicate regole decisionali uniformi: la definizione di caso è stata accreditata solo se confermata in laboratorio o basata su codici validati (gli algoritmi ICD/claims non validati non ricevono la stella); le stelle di comparabilità richiedono appaiamento o aggiustamento per età/sesso (prima stella) e per ulteriori confondenti chiave (seconda stella), per cui gli studi la cui stima curata non è aggiustata oltre l’appaiamento ricevono una sola stella; per le coorti, la completezza del follow-up è stata accreditata solo per sistemi sanitari chiusi (HMO, claims o registri di popolazione). Valutazioni complessive: 7-9 stelle = rischio di bias <strong>basso</strong>, 5-6 = <strong>alcune perplessità</strong>, 4 o meno = <strong>alto</strong>. I punteggi per singolo item e le giustificazioni per studio sono registrati in <code>nos_assessment.csv</code>.</p>
</div>
<table class="caption-top">
<colgroup>
<col style="width: 14%" />
<col style="width: 10%" />
<col style="width: 7%" />
<col style="width: 12%" />
<col style="width: 15%" />
<col style="width: 18%" />
<col style="width: 9%" />
<col style="width: 11%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Study</th>
<th style="text-align: left;">Design</th>
<th style="text-align: left;">Set</th>
<th style="text-align: right;">Selection (0-4)</th>
<th style="text-align: right;">Comparability (0-2)</th>
<th style="text-align: right;">Outcome/Exposure (0-3)</th>
<th style="text-align: right;">Total (0-9)</th>
<th style="text-align: left;">Overall RoB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Adams2017">(<a href="#ref-Adams2017" role="doc-biblioref">Adams et al. 2017</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Tartof2015">(<a href="#ref-Tartof2015" role="doc-biblioref">Tartof et al. 2015</a>)</span></td>
<td style="text-align: left;">cohort</td>
<td style="text-align: left;">secondary</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Baxter2008">(<a href="#ref-Baxter2008" role="doc-biblioref">Baxter et al. 2008</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Boven2026">(<a href="#ref-Boven2026" role="doc-biblioref">Boven et al. 2026</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Brown2016">(<a href="#ref-Brown2016" role="doc-biblioref">Brown et al. 2016</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">secondary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Carmichael2023">(<a href="#ref-Carmichael2023" role="doc-biblioref">Carmichael et al. 2023</a>)</span></td>
<td style="text-align: left;">cohort</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Delaney2007">(<a href="#ref-Delaney2007" role="doc-biblioref">Delaney et al. 2007</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">secondary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Dial2008">(<a href="#ref-Dial2008" role="doc-biblioref">Dial et al. 2008</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">secondary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Guh2015">(<a href="#ref-Guh2015" role="doc-biblioref">Guh et al. 2017</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">secondary</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Kuntz2011">(<a href="#ref-Kuntz2011" role="doc-biblioref">Kuntz et al. 2011</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Miller2023">(<a href="#ref-Miller2023" role="doc-biblioref">Miller et al. 2023</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="OLeary2023">(<a href="#ref-OLeary2023" role="doc-biblioref">O’Leary et al. 2023</a>)</span></td>
<td style="text-align: left;">cohort</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Saito2025">(<a href="#ref-Saito2025" role="doc-biblioref">Saito et al. 2025</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Strom2017">(<a href="#ref-Strom2017" role="doc-biblioref">Ström et al. 2017</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">secondary</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Watson2018">(<a href="#ref-Watson2018" role="doc-biblioref">Watson et al. 2018</a>)</span></td>
<td style="text-align: left;">cohort</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Webb2020">(<a href="#ref-Webb2020" role="doc-biblioref">Webb et al. 2020</a>)</span></td>
<td style="text-align: left;">cohort</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Doernberg2012">(<a href="#ref-Doernberg2012" role="doc-biblioref">Doernberg et al. 2012</a>)</span></td>
<td style="text-align: left;">cohort</td>
<td style="text-align: left;">primary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Tilton2019">(<a href="#ref-Tilton2019" role="doc-biblioref">Tilton and Johnson 2019</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">secondary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="Yu2021">(<a href="#ref-Yu2021" role="doc-biblioref">Yu et al. 2021</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">secondary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="Predrag2016">(<a href="#ref-Predrag2016" role="doc-biblioref">Stojanović 2016</a>)</span></td>
<td style="text-align: left;">case-control</td>
<td style="text-align: left;">secondary</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Some concerns</td>
</tr>
</tbody>
</table>
<div class="cap">
<div class="en">
<p><strong>Table 2.</strong> Newcastle-Ottawa assessment of the 20 studies in the synthesis (domain subtotals; maxima 4/2/3 stars, 9 overall). Selection covers case/cohort definition, representativeness, comparison-group selection and absence of the outcome at baseline (definition of controls for case-control studies); Outcome/Exposure covers ascertainment of outcome (cohorts) or exposure (case-control studies), comparability of ascertainment across groups, and follow-up/non-response.</p>
</div>
<div class="it">
<p><strong>Tabella 2.</strong> Valutazione Newcastle-Ottawa dei 20 studi della sintesi (subtotali per dominio; massimi 4/2/3 stelle, 9 complessive). La selezione copre definizione di caso/coorte, rappresentatività, selezione del gruppo di confronto e assenza dell’esito al baseline (definizione dei controlli per i caso-controllo); Esito/Esposizione copre l’accertamento dell’esito (coorti) o dell’esposizione (caso-controllo), la comparabilità dell’accertamento tra i gruppi e il follow-up/non-risposta.</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img src="report_files/figure-html/rob-plot-1.png" class="img-fluid" width="624" /></p>
</figure>
</div>
</div>
</div>
<div class="cap">
<div class="en">
<p><strong>Traffic-light plot.</strong> Domain-level risk-of-bias ratings. Domain rules: Selection low if at least 3 of 4 stars; Comparability low with 2 stars, some concerns with 1; Outcome/Exposure low with 3 stars, some concerns with 2. Overall: 7-9 low, 5-6 some concerns, 4 or fewer high.</p>
</div>
<div class="it">
<p><strong>Traffic-light plot.</strong> Valutazioni di rischio di bias per dominio. Regole: Selezione bassa con almeno 3 stelle su 4; Comparabilità bassa con 2 stelle, alcune perplessità con 1; Esito/Esposizione bassa con 3 stelle, alcune perplessità con 2. Complessivo: 7-9 basso, 5-6 alcune perplessità, 4 o meno alto.</p>
</div>
</div>
<div class="en">
<p>19 of 20 studies reach 7 or more stars (low risk of bias). Recurring limitations are case definitions based on unvalidated diagnostic codes (selection), hospital-based controls in smaller case-control studies (selection), reliance on unadjusted per-drug estimates (comparability), and uncertain completeness of post-discharge outcome capture in hospital-discharge cohorts (outcome). For the six studies carried forward from Tariq et al. (2018), our independent scores (median 8, range 7-9) are consistent with theirs (median 7, range 7-8) <span class="citation" data-cites="Tariq2018">(<a href="#ref-Tariq2018" role="doc-biblioref">Tariq and Khanna 2018</a>)</span>.</p>
<p>The pre-specified sensitivity analysis excluding studies at higher risk of bias (NOS below 7) removes only Predrag 2016: the primary estimate is unchanged because all 11 antibiotic-comparator studies are low risk (OR 0.86 (0.60–1.23)), and the secondary, no-antibiotic comparison becomes OR 1.05 (0.74–1.54) (k = 8). Conclusions are therefore robust to study quality as assessed here.</p>
</div>
<div class="it">
<p>19 studi su 20 raggiungono almeno 7 stelle (basso rischio di bias). Le limitazioni ricorrenti sono definizioni di caso basate su codici diagnostici non validati (selezione), controlli ospedalieri negli studi caso-controllo più piccoli (selezione), affidamento a stime per singolo farmaco non aggiustate (comparabilità) e incerta completezza della cattura dell’esito dopo la dimissione nelle coorti ospedaliere (esito). Per i sei studi trasferiti da Tariq et al. (2018), i nostri punteggi indipendenti (mediana 8, intervallo 7-9) sono coerenti con i loro (mediana 7, intervallo 7-8) <span class="citation" data-cites="Tariq2018">(<a href="#ref-Tariq2018" role="doc-biblioref">Tariq and Khanna 2018</a>)</span>.</p>
<p>L’analisi di sensibilità pre-specificata che esclude gli studi a maggior rischio di bias (NOS inferiore a 7) rimuove solo Predrag 2016: la stima primaria è invariata perché tutti gli 11 studi con comparatore antibiotico sono a basso rischio (OR 0.86 (0.60–1.23)), e il confronto secondario (vs nessun antibiotico) diventa OR 1.05 (0.74–1.54) (k = 8). Le conclusioni sono quindi robuste rispetto alla qualità degli studi così come valutata qui.</p>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<div class="en">
<p><strong>Provisional assessment.</strong> The protocol requires independent, duplicate full-text assessment by two reviewers. The scores above are a single-reviewer assessment based on the extraction database — whose covariate matrix is still unpopulated and whose estimate rows are all marked unverified — and should be re-confirmed against the full articles before being considered final.</p>
</div>
<div class="it">
<p><strong>Valutazione provvisoria.</strong> Il protocollo richiede una valutazione indipendente, in doppio, sul full-text da parte di due revisori. I punteggi sopra riportati derivano da una valutazione di un singolo revisore basata sul database di estrazione — la cui matrice delle covariate non è ancora popolata e le cui righe di stima risultano tutte non verificate — e devono essere riconfermati sugli articoli integrali prima di essere considerati definitivi.</p>
</div>
</div>
</div>
</section>
<section id="methodsmetodi" class="level2">
<h2><span class="en">Methods</span><span class="it">Metodi</span></h2>
<div class="en">
<p>Hierarchical random-effects model on the log-odds scale: <span class="math display">\[y_i \sim \text{Normal}(\theta_i, s_i^2), \qquad \theta_i \sim \text{Normal}(\mu, \tau^2).\]</span> Primary prior <span class="math inline">\(\mu \sim \text{Normal}(0, 1^2)\)</span>; heterogeneity prior <span class="math inline">\(\tau \sim \text{Half-Normal}(0, 0.5)\)</span>. Posteriors were computed exactly by numerical integration (<code>bayesmeta</code>) and independently confirmed by Hamiltonian Monte Carlo (<code>brms</code>/Stan, 4 chains). We report the pooled odds ratio (OR = exp <span class="math inline">\(\mu\)</span>) with a 95% credible interval (CrI), the between-study SD <span class="math inline">\(\tau\)</span>, the predictive interval for a new study, and the posterior probabilities P(OR&lt;1) and P(OR&lt;0.80). A pre-specified prior-sensitivity analysis used vague, sceptical and literature-informed priors.</p>
</div>
<div class="it">
<p>Modello gerarchico a effetti casuali su scala log-odds: <span class="math display">\[y_i \sim \text{Normale}(\theta_i, s_i^2), \qquad \theta_i \sim \text{Normale}(\mu, \tau^2).\]</span> Prior primario <span class="math inline">\(\mu \sim \text{Normale}(0, 1^2)\)</span>; prior sull’eterogeneità <span class="math inline">\(\tau \sim \text{Half-Normale}(0, 0.5)\)</span>. Le distribuzioni a posteriori sono state calcolate in modo esatto per integrazione numerica (<code>bayesmeta</code>) e confermate in modo indipendente con Hamiltonian Monte Carlo (<code>brms</code>/Stan, 4 catene). Riportiamo l’odds ratio aggregato (OR = exp <span class="math inline">\(\mu\)</span>) con intervallo di credibilità (ICr) al 95%, la deviazione standard tra studi <span class="math inline">\(\tau\)</span>, l’intervallo predittivo per un nuovo studio e le probabilità a posteriori P(OR&lt;1) e P(OR&lt;0,80). Un’analisi di sensibilità sui prior pre-specificata ha usato prior vago, scettico e informato dalla letteratura.</p>
</div>
</section>
<section id="primary-result-11-studiesrisultato-primario-11-studi" class="level2">
<h2><span class="en">Primary result (11 studies)</span><span class="it">Risultato primario (11 studi)</span></h2>
<div class="card">
<div class="en">
<p>Pooled odds ratio (tetracyclines vs other antibiotics) <span class="big">0.86 (0.60–1.23)</span></p>
<p>The 95% credible interval crosses 1. The posterior probability of any protective effect is <strong>P(OR&lt;1) = 0.81</strong>, and the probability of a clinically meaningful effect is <strong>P(OR&lt;0.80) = 0.35</strong>. Between-study heterogeneity is substantial (<span class="math inline">\(\tau\)</span> = 0.55 (0.34–0.83); I² = 98% (95% CrI 96–99%)): the predictive interval for a future study spans OR 0.25–2.88.</p>
</div>
<div class="it">
<p>Odds ratio aggregato (tetracicline vs altri antibiotici) <span class="big">0.86 (0.60–1.23)</span></p>
<p>L’intervallo di credibilità al 95% attraversa 1. La probabilità a posteriori di un qualsiasi effetto protettivo è <strong>P(OR&lt;1) = 0.81</strong>, e la probabilità di un effetto clinicamente rilevante è <strong>P(OR&lt;0,80) = 0.35</strong>. L’eterogeneità tra studi è sostanziale (<span class="math inline">\(\tau\)</span> = 0.55 (0.34–0.83); I² = 98% (95% CrI 96–99%)): l’intervallo predittivo per uno studio futuro va da OR 0.25–2.88.</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-forest" class="quarto-float quarto-figure quarto-figure-center" width="768">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-forest-1.png" id="fig-forest" class="img-fluid" width="768" />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 1
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cap">
<div class="en">
<p><strong>Figure 1.</strong> Study-level odds ratios (primary set, 11 studies with antibiotic comparators). Gray = observed estimates; blue = Bayesian posterior (shrinkage) estimates, pulled toward the pooled mean. The navy line and blue band show the pooled OR (primary prior) and 95% credible interval. The dotted and long-dashed vertical lines mark the pooled OR under the sceptical and literature-informed priors; the faint outer band is the prior-sensitivity range.</p>
</div>
<div class="it">
<p><strong>Figura 1.</strong> Odds ratio per studio (set primario, 11 studi con comparatori antibiotici). Grigio = stime osservate; blu = stime a posteriori bayesiane (shrinkage), attratte verso la media aggregata. La linea navy e la banda blu indicano l’OR aggregato (prior primario) e l’ICr al 95%. Le linee verticali punteggiata e tratteggiata indicano l’OR aggregato con i prior scettico e informato dalla letteratura; la banda esterna tenue è l’intervallo di sensibilità ai prior.</p>
</div>
</div>
</section>
<section id="prior-sensitivitysensibilità-ai-prior" class="level2">
<h2><span class="en">Prior sensitivity</span><span class="it">Sensibilità ai prior</span></h2>
<div class="en">
<p>The estimate is stable across data-dominated priors (primary, vague, sceptical) but shifts toward protection under the literature-informed prior centred on the earlier Tariq (2018) estimate of OR 0.62 — i.e. that conclusion is driven by prior belief, not the new data.</p>
</div>
<div class="it">
<p>La stima è stabile tra i prior dominati dai dati (primario, vago, scettico) ma si sposta verso la protezione con il prior informato dalla letteratura, centrato sulla stima precedente di Tariq (2018), OR 0,62 — cioè quella conclusione è guidata dalla convinzione a priori, non dai nuovi dati.</p>
</div>
<div class="en">
<div class="cell">
<div id="tbl-prior-en" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-prior-en-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 1
</figcaption>
<div aria-describedby="tbl-prior-en-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 45%" />
<col style="width: 25%" />
<col style="width: 12%" />
<col style="width: 16%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Prior on μ</th>
<th style="text-align: center;">OR (95% CrI)</th>
<th style="text-align: center;">P(OR&lt;1)</th>
<th style="text-align: center;">P(OR&lt;0.80)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Primary — N(0, 1²)</td>
<td style="text-align: center;">0.86 (0.60–1.23)</td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vague — N(0, 10²)</td>
<td style="text-align: center;">0.85 (0.59–1.23)</td>
<td style="text-align: center;">0.82</td>
<td style="text-align: center;">0.36</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sceptical — N(0, 0.35²)</td>
<td style="text-align: center;">0.88 (0.64–1.21)</td>
<td style="text-align: center;">0.79</td>
<td style="text-align: center;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: left;">Literature — N(log 0.62, 0.10²)</td>
<td style="text-align: center;">0.67 (0.56–0.80)</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.98</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="it">
<div class="cell">
<div id="tbl-prior-it" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-prior-it-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 2
</figcaption>
<div aria-describedby="tbl-prior-it-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 45%" />
<col style="width: 25%" />
<col style="width: 12%" />
<col style="width: 16%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Prior su μ</th>
<th style="text-align: center;">OR (ICr 95%)</th>
<th style="text-align: center;">P(OR&lt;1)</th>
<th style="text-align: center;">P(OR&lt;0,80)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Primario — N(0, 1²)</td>
<td style="text-align: center;">0.86 (0.60–1.23)</td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vago — N(0, 10²)</td>
<td style="text-align: center;">0.85 (0.59–1.23)</td>
<td style="text-align: center;">0.82</td>
<td style="text-align: center;">0.36</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scettico — N(0, 0,35²)</td>
<td style="text-align: center;">0.88 (0.64–1.21)</td>
<td style="text-align: center;">0.79</td>
<td style="text-align: center;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: left;">Letteratura — N(log 0,62, 0,10²)</td>
<td style="text-align: center;">0.67 (0.56–0.80)</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.98</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="prior-data-conflictconflitto-prior-dati" class="level2">
<h2><span class="en">Prior-data conflict</span><span class="it">Conflitto prior-dati</span></h2>
<div class="en">
<p>Because the literature-informed prior is the only assumption under which the result becomes confidently protective, we formally check whether it conflicts with the updated data. Using the Box / Marshall-Spiegelhalter measure, we compare the prior for μ — N(log 0.62, 0.10²), i.e. OR 0.62 — against the data-only estimate (vague-prior posterior: OR 0.85, log-scale mean -0.16, SD 0.19). The conflict statistic is z = -1.50 (two-sided p = 0.13), indicating <strong>mild tension but no formal conflict</strong>. The literature prior is more optimistic than the updated evidence, but the gap is within sampling variation. Its influence on the pooled estimate comes mainly from being far narrower (SD 0.10) than the data-only posterior (SD 0.19) rather than from statistical incompatibility with the data.</p>
</div>
<div class="it">
<p>Poiché il prior informato dalla letteratura è l’unica assunzione sotto cui il risultato diventa decisamente protettivo, verifichiamo formalmente se sia in conflitto con i dati aggiornati. Con la misura di Box / Marshall-Spiegelhalter confrontiamo il prior per μ — N(log 0,62, 0,10²), cioè OR 0,62 — con la stima basata sui soli dati (posteriori con prior vago: OR 0.85, media log -0.16, SD 0.19). La statistica di conflitto è z = -1.50 (p bilaterale = 0.13), indicando <strong>una lieve tensione ma nessun conflitto formale</strong>. Il prior della letteratura è più ottimistico delle evidenze aggiornate, ma la differenza rientra nella variabilità campionaria. La sua influenza deriva soprattutto dall’essere molto più stretto (SD 0,10) della posteriori basata sui dati (SD 0.19), non da un’incompatibilità statistica con i dati.</p>
</div>
</section>
<section id="mcmc-confirmation-convergenceconferma-mcmc-e-convergenza" class="level2">
<h2><span class="en">MCMC confirmation &amp; convergence</span><span class="it">Conferma MCMC e convergenza</span></h2>
<div class="en">
<p>The two engines agree to within Monte Carlo error, confirming the exact posterior. All diagnostics indicate good convergence.</p>
</div>
<div class="it">
<p>I due motori concordano entro l’errore Monte Carlo, confermando la posteriori esatta. Tutti gli indici indicano una buona convergenza.</p>
</div>
<div class="en">
<div class="cell">
<div id="tbl-confirm-en" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-confirm-en-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 3
</figcaption>
<div aria-describedby="tbl-confirm-en-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: center;">OR (95% CrI)</th>
<th style="text-align: center;">τ</th>
<th style="text-align: center;">P(OR&lt;1)</th>
<th style="text-align: center;">P(OR&lt;0.80)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">bayesmeta (exact)</td>
<td style="text-align: center;">0.86 (0.60–1.23)</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">brms (MCMC)</td>
<td style="text-align: center;">0.85 (0.60–1.23)</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">0.36</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">R-hat</th>
<th style="text-align: center;">Bulk ESS</th>
<th style="text-align: center;">Tail ESS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">μ (log-OR)</td>
<td style="text-align: center;">1.000</td>
<td style="text-align: center;">2516</td>
<td style="text-align: center;">3702</td>
</tr>
<tr class="even">
<td style="text-align: left;">τ (heterogeneity SD)</td>
<td style="text-align: center;">1.000</td>
<td style="text-align: center;">3217</td>
<td style="text-align: center;">5375</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="it">
<div class="cell">
<div id="tbl-confirm-it" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-confirm-it-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 4
</figcaption>
<div aria-describedby="tbl-confirm-it-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Metodo</th>
<th style="text-align: center;">OR (ICr 95%)</th>
<th style="text-align: center;">τ</th>
<th style="text-align: center;">P(OR&lt;1)</th>
<th style="text-align: center;">P(OR&lt;0,80)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">bayesmeta (exact)</td>
<td style="text-align: center;">0.86 (0.60–1.23)</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">brms (MCMC)</td>
<td style="text-align: center;">0.85 (0.60–1.23)</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">0.36</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Parametro</th>
<th style="text-align: center;">R-hat</th>
<th style="text-align: center;">ESS bulk</th>
<th style="text-align: center;">ESS tail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">μ (log-OR)</td>
<td style="text-align: center;">1.000</td>
<td style="text-align: center;">2516</td>
<td style="text-align: center;">3702</td>
</tr>
<tr class="even">
<td style="text-align: left;">τ (SD eterogeneità)</td>
<td style="text-align: center;">1.000</td>
<td style="text-align: center;">3217</td>
<td style="text-align: center;">5375</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-trace" class="quarto-float quarto-figure quarto-figure-center" width="768">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-trace-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-trace-1.png" id="fig-trace" class="img-fluid" width="768" />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-trace-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 2
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cap">
<div class="en">
<p><strong>Figure 2.</strong> MCMC trace plots for the four chains (pooled log-OR and heterogeneity SD).</p>
</div>
<div class="it">
<p><strong>Figura 2.</strong> Trace plot MCMC per le quattro catene (log-OR aggregato e SD dell’eterogeneità).</p>
</div>
</div>
</section>
<section id="small-study-effectseffetti-dei-piccoli-studi" class="level2">
<h2><span class="en">Small-study effects</span><span class="it">Effetti dei piccoli studi</span></h2>
<div class="en">
<p>With k = 11 studies (meeting the pre-specified ≥10 threshold), a contour-enhanced funnel plot and Egger’s regression test assess funnel asymmetry. There is <strong>no evidence of asymmetry</strong> (Egger z = -0.28, p = 0.78); the studies scatter fairly symmetrically about the pooled effect. Given the observational evidence base and modest k, this is reassuring but not decisive.</p>
</div>
<div class="it">
<p>Con k = 11 studi (soglia pre-specificata ≥10), un funnel plot contour-enhanced e il test di regressione di Egger valutano l’asimmetria. <strong>Non vi è evidenza di asimmetria</strong> (Egger z = -0.28, p = 0.78); gli studi si distribuiscono in modo abbastanza simmetrico attorno all’effetto aggregato. Data la natura osservazionale e il k contenuto, è rassicurante ma non decisivo.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-funnel" class="quarto-float quarto-figure quarto-figure-center" width="672">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-funnel-1.png" id="fig-funnel" class="img-fluid" width="672" />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 3
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cap">
<div class="en">
<p><strong>Figure 3.</strong> Contour-enhanced funnel plot; shaded bands mark the p = 0.10 / 0.05 / 0.01 regions.</p>
</div>
<div class="it">
<p><strong>Figura 3.</strong> Funnel plot contour-enhanced; le bande indicano le regioni p = 0,10 / 0,05 / 0,01.</p>
</div>
</div>
</section>
<section id="leave-one-outanalisi-leave-one-out" class="level2">
<h2><span class="en">Leave-one-out</span><span class="it">Analisi leave-one-out</span></h2>
<div class="en">
<p>No single study drives the pooled estimate: removing any one study leaves the pooled OR between 0.75 and 0.93, always below 1. The most influential study is Saito 2025 (a harmful outlier); dropping it moves the OR most toward protection, while dropping the protective Watson 2018 moves it toward the null. The qualitative conclusion is stable throughout.</p>
</div>
<div class="it">
<p>Nessun singolo studio determina la stima aggregata: rimuovendo un qualsiasi studio l’OR aggregato resta tra 0.75 e 0.93, sempre inferiore a 1. Lo studio più influente è Saito 2025 (un outlier sfavorevole): la sua rimozione sposta l’OR verso la protezione, mentre rimuovere il protettivo Watson 2018 lo sposta verso l’assenza di effetto. La conclusione qualitativa resta stabile.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-loo" class="quarto-float quarto-figure quarto-figure-center" width="768">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-loo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-loo-1.png" id="fig-loo" class="img-fluid" width="768" />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-loo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 4
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cap">
<div class="en">
<p><strong>Figure 4.</strong> Leave-one-out pooled OR; the blue line and band are the full k = 11 estimate and 95% CrI.</p>
</div>
<div class="it">
<p><strong>Figura 4.</strong> OR aggregato leave-one-out; la linea e la banda blu sono la stima completa k = 11 e l’ICr al 95%.</p>
</div>
</div>
</section>
<section id="doxycycline-only-sensitivity-analysisanalisi-di-sensibilità-sola-doxiciclina" class="level2">
<h2><span class="en">Doxycycline-only sensitivity analysis</span><span class="it">Analisi di sensibilità: sola doxiciclina</span></h2>
<div class="en">
<p>Doxycycline is the dominant tetracycline in the evidence base and the agent most often invoked for anaerobe-sparing activity, so we pre-specified a sensitivity analysis restricting the primary antibiotic-comparator set to doxycycline-exposure studies (k = 6), keeping the primary prior. The pooled odds ratio is <strong>0.78 (0.56–1.02)</strong> with P(OR&lt;1) = 0.97 and P(OR&lt;0.80) = 0.56. Restricting to a single agent roughly halves the between-study heterogeneity (τ = 0.27 vs 0.55 in the full primary set) and tightens the predictive interval for a new study to OR 0.36–1.59. The doxycycline estimate is more precise and more consistently below 1 than the all-tetracycline estimate, but its 95% credible interval still touches 1 — a stronger, yet still not definitive, protective signal.</p>
</div>
<div class="it">
<p>La doxiciclina è la tetraciclina prevalente nella base di evidenze e l’agente più spesso citato per l’attività di risparmio degli anaerobi; abbiamo quindi pre-specificato un’analisi di sensibilità che limita il set primario con comparatore antibiotico agli studi con esposizione a doxiciclina (k = 6), mantenendo il prior primario. L’odds ratio aggregato è <strong>0.78 (0.56–1.02)</strong> con P(OR&lt;1) = 0.97 e P(OR&lt;0,80) = 0.56. Limitarsi a un singolo agente dimezza circa l’eterogeneità tra studi (τ = 0.27 vs 0.55 nel set primario completo) e restringe l’intervallo predittivo per un nuovo studio a OR 0.36–1.59. La stima per la doxiciclina è più precisa e più costantemente inferiore a 1 rispetto alla stima su tutte le tetracicline, ma il suo intervallo di credibilità al 95% tocca ancora 1 — un segnale protettivo più forte, ma non ancora definitivo.</p>
</div>
<div class="en">
<div class="cell">
<div id="tbl-doxy-en" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-doxy-en-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 5
</figcaption>
<div aria-describedby="tbl-doxy-en-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 32%" />
<col style="width: 15%" />
<col style="width: 20%" />
<col style="width: 6%" />
<col style="width: 10%" />
<col style="width: 13%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Analysis</th>
<th style="text-align: center;">Studies (k)</th>
<th style="text-align: center;">OR (95% CrI)</th>
<th style="text-align: center;">τ</th>
<th style="text-align: center;">P(OR&lt;1)</th>
<th style="text-align: center;">P(OR&lt;0.80)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">All tetracyclines (primary)</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">0.86 (0.60–1.23)</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">Doxycycline only</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.78 (0.56–1.02)</td>
<td style="text-align: center;">0.27</td>
<td style="text-align: center;">0.97</td>
<td style="text-align: center;">0.56</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="it">
<div class="cell">
<div id="tbl-doxy-it" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-doxy-it-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 6
</figcaption>
<div aria-describedby="tbl-doxy-it-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 37%" />
<col style="width: 12%" />
<col style="width: 20%" />
<col style="width: 6%" />
<col style="width: 10%" />
<col style="width: 13%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Analisi</th>
<th style="text-align: center;">Studi (k)</th>
<th style="text-align: center;">OR (ICr 95%)</th>
<th style="text-align: center;">τ</th>
<th style="text-align: center;">P(OR&lt;1)</th>
<th style="text-align: center;">P(OR&lt;0,80)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Tutte le tetracicline (primario)</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">0.86 (0.60–1.23)</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">Solo doxiciclina</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.78 (0.56–1.02)</td>
<td style="text-align: center;">0.27</td>
<td style="text-align: center;">0.97</td>
<td style="text-align: center;">0.56</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="cap">
<div class="en">
<p><strong>Table 2.</strong> Doxycycline-only sensitivity analysis versus the full primary set. Restricting to doxycycline exposure lowers heterogeneity and sharpens the protective signal, though the credible interval still includes OR = 1.</p>
</div>
<div class="it">
<p><strong>Tabella 2.</strong> Analisi di sensibilità sulla sola doxiciclina rispetto al set primario completo. Limitarsi all’esposizione a doxiciclina riduce l’eterogeneità e rende più netto il segnale protettivo, benché l’intervallo di credibilità includa ancora OR = 1.</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-doxy" class="quarto-float quarto-figure quarto-figure-center" width="720">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-doxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-doxy-1.png" id="fig-doxy" class="img-fluid" width="720" />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-doxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 5
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cap">
<div class="en">
<p><strong>Figure 5.</strong> Forest plot of the doxycycline-only sensitivity analysis. Gray points are the six doxycycline-exposure studies (observed ORs, 95% CIs); navy points are the pooled Bayesian estimates for the doxycycline-only subset (k = 6) and the full primary set (k = 11). The shaded band is the doxycycline-only 95% credible interval; the dashed line marks OR = 1.</p>
</div>
<div class="it">
<p><strong>Figura 5.</strong> Forest plot dell’analisi di sensibilità sulla sola doxiciclina. I punti grigi sono i sei studi con esposizione a doxiciclina (OR osservati, IC 95%); i punti navy sono le stime bayesiane aggregate per il sottoinsieme doxiciclina (k = 6) e per il set primario completo (k = 11). La banda ombreggiata è l’intervallo di credibilità al 95% della sola doxiciclina; la linea tratteggiata indica OR = 1.</p>
</div>
</div>
</section>
<section id="additional-sensitivity-analysesanalisi-di-sensibilità-aggiuntive" class="level2">
<h2><span class="en">Additional sensitivity analyses</span><span class="it">Analisi di sensibilità aggiuntive</span></h2>
<div class="en">
<p><strong>Adjusted-only secondary comparison.</strong> Restricting the no-antibiotic comparison to the three studies with multivariable-adjusted estimates (Delaney 2007, Dial 2008, Brown 2016) gives OR 1.10 (0.62–1.88) (k = 3), P(OR&lt;1) = 0.34 — consistent with the full secondary set, with a wider interval reflecting the smaller evidence base.</p>
<p><strong>Excluding ratio-metric conversions.</strong> The curated estimates of Doernberg 2012 (adjusted HR), Dial 2008 (adjusted RR) and Brown 2016 (adjusted IRR) enter the analysis as ORs under a rare-outcome approximation. Excluding them leaves the primary estimate essentially unchanged (k = 10; OR 0.87 (0.59–1.29), P(OR&lt;1) = 0.77) and the secondary estimate likewise (k = 7; OR 1.01 (0.67–1.60), P(OR&lt;1) = 0.49). Conclusions are robust to this approximation.</p>
</div>
<div class="it">
<p><strong>Confronto secondario con sole stime aggiustate.</strong> Limitando il confronto contro nessun antibiotico ai tre studi con stime aggiustate multivariabili (Delaney 2007, Dial 2008, Brown 2016) si ottiene OR 1.10 (0.62–1.88) (k = 3), P(OR&lt;1) = 0.34 — coerente con l’intero set secondario, con un intervallo più ampio che riflette la base di evidenze ridotta.</p>
<p><strong>Esclusione delle conversioni da misure di tasso/rischio.</strong> Le stime curate di Doernberg 2012 (HR aggiustato), Dial 2008 (RR aggiustato) e Brown 2016 (IRR aggiustato) entrano nell’analisi come OR tramite un’approssimazione per esiti rari. Escludendole, la stima primaria resta sostanzialmente invariata (k = 10; OR 0.87 (0.59–1.29), P(OR&lt;1) = 0.77), così come quella secondaria (k = 7; OR 1.01 (0.67–1.60), P(OR&lt;1) = 0.49). Le conclusioni sono robuste rispetto a questa approssimazione.</p>
</div>
</section>
<section id="secondary-comparison-vs-no-antibiotic-9-studiesconfronto-secondario-vs-nessun-antibiotico-9-studi" class="level2">
<h2><span class="en">Secondary comparison: vs no antibiotic (9 studies)</span><span class="it">Confronto secondario: vs nessun antibiotico (9 studi)</span></h2>
<div class="en">
<p>Against a <em>no-antibiotic</em> comparator the association is essentially null (<strong>OR 1.06 (0.75–1.53)</strong>, P(OR&lt;1) = 0.36). This is expected — almost any antibiotic raises CDI risk relative to no antibiotic — and it explains why pooling these studies into the primary set attenuated the protective signal. The two comparator questions are distinct and should not be combined.</p>
</div>
<div class="it">
<p>Rispetto a un comparatore <em>senza antibiotico</em> l’associazione è sostanzialmente nulla (<strong>OR 1.06 (0.75–1.53)</strong>, P(OR&lt;1) = 0.36). È un risultato atteso — quasi ogni antibiotico aumenta il rischio di ICD rispetto a nessun antibiotico — e spiega perché aggregare questi studi nel set primario attenuava il segnale protettivo. Le due domande sul comparatore sono distinte e non vanno combinate.</p>
</div>
</section>
<section id="subgroupssottogruppi" class="level2">
<h2><span class="en">Subgroups</span><span class="it">Sottogruppi</span></h2>
<div class="en">
<p>Within the primary set, the doxycycline-restricted subgroup and cohort studies lean protective, whereas case-control studies do not — a design-related divergence that warrants cautious interpretation.</p>
</div>
<div class="it">
<p>All’interno del set primario, il sottogruppo limitato alla doxiciclina e gli studi di coorte tendono alla protezione, mentre gli studi caso-controllo no: una divergenza legata al disegno da interpretare con cautela.</p>
</div>
<div class="en">
<div class="cell">
<div id="tbl-sub-en" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-sub-en-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 7
</figcaption>
<div aria-describedby="tbl-sub-en-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Analysis</th>
<th style="text-align: center;">Studies (k)</th>
<th style="text-align: center;">OR (95% CrI)</th>
<th style="text-align: center;">P(OR&lt;1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Doxycycline only</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.78 (0.56–1.02)</td>
<td style="text-align: center;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case-control designs</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1.05 (0.60–1.82)</td>
<td style="text-align: center;">0.42</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cohort designs</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.69 (0.46–1.03)</td>
<td style="text-align: center;">0.97</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="it">
<div class="cell">
<div id="tbl-sub-it" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-sub-it-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 8
</figcaption>
<div aria-describedby="tbl-sub-it-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Analisi</th>
<th style="text-align: center;">Studi (k)</th>
<th style="text-align: center;">OR (ICr 95%)</th>
<th style="text-align: center;">P(OR&lt;1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Solo doxiciclina</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.78 (0.56–1.02)</td>
<td style="text-align: center;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">Disegni caso-controllo</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1.05 (0.60–1.82)</td>
<td style="text-align: center;">0.42</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Disegni di coorte</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.69 (0.46–1.03)</td>
<td style="text-align: center;">0.97</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="care-context-meta-regressionmeta-regressione-per-contesto-assistenziale" class="level2">
<h2><span class="en">Care-context meta-regression</span><span class="it">Meta-regressione per contesto assistenziale</span></h2>
<div class="en">
<p>A pre-specified Bayesian meta-regression (exact, <code>bmr</code>) on the <strong>primary antibiotic-comparator set (k = 11)</strong> estimates a separate pooled OR per care context (CA 3, HA 4, mixed 4). The protective association is concentrated in <strong>hospital-acquired (inpatient) settings</strong> (OR 0.56 (0.33–0.94), P(OR&lt;1) = 0.98), while community-acquired and mixed settings straddle 1. This mirrors Tariq (2018), whose setting subgroup found protection in inpatients (OR 0.55) but not mixed populations (OR 0.92). As a <strong>sensitivity analysis on the full primary set (k = 20; CA 6, HA 9, mixed 5)</strong>, the hospital-acquired estimate attenuates to OR 0.79 (0.54–1.17) (P(OR&lt;1) = 0.88), because that set adds no-antibiotic-comparator studies that dilute the setting contrast. Per-group counts are small, so this is exploratory; residual heterogeneity remains (τ = 0.47).</p>
</div>
<div class="it">
<p>Una meta-regressione bayesiana pre-specificata (esatta, <code>bmr</code>) sul <strong>set primario con comparatore antibiotico (k = 11)</strong> stima un OR aggregato per ciascun contesto (CA 3, HA 4, misto 4). L’associazione protettiva si concentra nei <strong>contesti ospedalieri (pazienti ricoverati)</strong> (OR 0.56 (0.33–0.94), P(OR&lt;1) = 0.98), mentre i contesti comunitari e misti attraversano 1. Ciò rispecchia Tariq (2018), la cui analisi per contesto trovava protezione nei ricoverati (OR 0,55) ma non nelle popolazioni miste (OR 0,92). Come <strong>analisi di sensibilità sul set primario completo (k = 20; CA 6, HA 9, misto 5)</strong>, la stima ospedaliera si attenua a OR 0.79 (0.54–1.17) (P(OR&lt;1) = 0.88), perché quel set aggiunge studi con comparatore “nessun antibiotico” che diluiscono il contrasto. Le numerosità per gruppo sono piccole, quindi è esplorativo; l’eterogeneità residua permane (τ = 0.47).</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-metareg" class="quarto-float quarto-figure quarto-figure-center" width="720">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-metareg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-metareg-1.png" id="fig-metareg" class="img-fluid" width="720" />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-metareg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 6
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cap">
<div class="en">
<p><strong>Figure 6.</strong> Care-context pooled ORs from the Bayesian meta-regression: primary antibiotic-comparator set (k = 11, blue) with full-set sensitivity (k = 20, gray).</p>
</div>
<div class="it">
<p><strong>Figura 6.</strong> OR aggregati per contesto dalla meta-regressione bayesiana: set primario con comparatore antibiotico (k = 11, blu) e sensibilità sul set completo (k = 20, grigio).</p>
</div>
</div>
</section>
<section id="comparison-with-tariq-2018confronto-con-tariq-2018" class="level2">
<h2><span class="en">Comparison with Tariq (2018)</span><span class="it">Confronto con Tariq (2018)</span></h2>
<div class="en">
<p><strong>Can our Bayesian approach reproduce Tariq?</strong> Yes. Applied to Tariq’s exact six studies, a DerSimonian-Laird model reproduces their result exactly (0.62 (0.47–0.81), I² = 53%), and our Bayesian model gives a near-identical point estimate (0.63 (0.45–0.94), P(OR&lt;1) = 0.98). The Bayesian credible interval is wider than Tariq’s confidence interval because it propagates the uncertainty in τ that is unavoidable with only six studies — the divergence is one of honest uncertainty, not of the point estimate.</p>
<p><strong>Why does the updated review not find clear protection?</strong> Chiefly the <strong>additional studies</strong>. Adding the eight newer antibiotic-comparator studies to Tariq’s six moves the pooled OR from ~0.63 to 0.82 (0.60–1.13) (P(OR&lt;1) = 0.89) and roughly doubles heterogeneity — and this bridge lands essentially on our primary estimate. The new evidence is dominated by very large administrative cohorts (e.g. Carmichael, Miller, Watson, Webb, Boven) whose estimates sit close to the null and carry substantial weight. Secondary contributors to the difference are (i) the <strong>method</strong> (Bayesian vs DL), which mainly widens intervals rather than shifting the centre; and (ii) <strong>comparator and estimate decisions</strong> — our protocol separates “vs other antibiotics” from “vs no antibiotic”, so three of Tariq’s six studies (Delaney, Dial, Tartof) move to the secondary set, and Tartof’s estimate differs (Tariq’s adjusted OR 0.50 vs our unadjusted 0.84).</p>
</div>
<div class="it">
<p><strong>Il nostro approccio bayesiano riproduce Tariq?</strong> Sì. Applicato ai sei studi esatti di Tariq, un modello DerSimonian-Laird ne riproduce esattamente il risultato (0.62 (0.47–0.81), I² = 53%), e il nostro modello bayesiano fornisce una stima puntuale quasi identica (0.63 (0.45–0.94), P(OR&lt;1) = 0.98). L’intervallo di credibilità bayesiano è più ampio dell’intervallo di confidenza di Tariq perché propaga l’incertezza su τ, inevitabile con soli sei studi: la differenza riguarda l’incertezza, non la stima puntuale.</p>
<p><strong>Perché la revisione aggiornata non trova una protezione netta?</strong> Soprattutto per gli <strong>studi aggiuntivi</strong>. Aggiungendo gli otto nuovi studi con comparatore antibiotico ai sei di Tariq, l’OR aggregato passa da ~0,63 a 0.82 (0.60–1.13) (P(OR&lt;1) = 0.89) e l’eterogeneità circa raddoppia — e questo “ponte” coincide sostanzialmente con la nostra stima primaria. Le nuove evidenze sono dominate da coorti amministrative molto grandi (es. Carmichael, Miller, Watson, Webb, Boven), con stime vicine al valore nullo e peso sostanziale. Contribuiscono in via secondaria (i) il <strong>metodo</strong> (bayesiano vs DL), che allarga gli intervalli più che spostare il centro; e (ii) le <strong>decisioni su comparatore e stime</strong> — il protocollo separa “vs altri antibiotici” da “vs nessun antibiotico”, per cui tre dei sei studi di Tariq (Delaney, Dial, Tartof) passano al set secondario, e la stima di Tartof differisce (OR aggiustato 0,50 di Tariq vs 0,84 non aggiustato nostro).</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tariq" class="quarto-float quarto-figure quarto-figure-center" width="768">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-tariq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-tariq-1.png" id="fig-tariq" class="img-fluid" width="768" />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-tariq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 7
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cap">
<div class="en">
<p><strong>Figure 7.</strong> From Tariq to the updated review: recapitulation and stepwise decomposition of the difference.</p>
</div>
<div class="it">
<p><strong>Figura 7.</strong> Da Tariq alla revisione aggiornata: recupero e decomposizione passo-passo della differenza.</p>
</div>
</div>
</section>
<section id="certainty-of-evidence-gradecertezza-delle-evidenze-grade" class="level2">
<h2><span class="en">Certainty of evidence (GRADE)</span><span class="it">Certezza delle evidenze (GRADE)</span></h2>
<div class="en">
<p>Certainty was rated following the GRADE approach <span class="citation" data-cites="Guyatt2008GRADE">(<a href="#ref-Guyatt2008GRADE" role="doc-biblioref">Guyatt et al. 2008</a>)</span>. Because all evidence is observational, both comparisons start at <em>low</em> certainty; each was rated down for serious inconsistency and serious imprecision, yielding <strong>very low</strong> certainty for both questions.</p>
</div>
<div class="en">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
</colgroup>
<thead>
<tr class="header">
<th>Outcome: incident CDI</th>
<th>k</th>
<th>Pooled OR (95% CrI)</th>
<th>Illustrative absolute effect*</th>
<th>Risk of bias</th>
<th>Inconsistency</th>
<th>Indirectness</th>
<th>Imprecision</th>
<th>Publication bias</th>
<th>Certainty</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tetracyclines vs other antibiotics</td>
<td>11</td>
<td>0.86 (0.60–1.23)</td>
<td>17 vs 20 per 1,000 (12–24)</td>
<td>Not seriousᵃ</td>
<td>Seriousᵇ</td>
<td>Not serious</td>
<td>Seriousᶜ</td>
<td>Undetectedᵈ</td>
<td><strong>Very low</strong></td>
</tr>
<tr class="even">
<td>Tetracyclines vs no antibiotic</td>
<td>9</td>
<td>1.06 (0.75–1.53)</td>
<td>5 vs 5 per 1,000 (4–8)</td>
<td>Not seriousᵃ</td>
<td>Seriousᵇ</td>
<td>Seriousᵉ</td>
<td>Seriousᶜ</td>
<td>Undetectedᵈ</td>
<td><strong>Very low</strong></td>
</tr>
</tbody>
</table>
<p>* Illustrative only: assumes a baseline risk of 20 per 1,000 antibiotic-exposed patients (hospital context) and 5 per 1,000 unexposed patients; absolute effects scale with the baseline risk. ᵃ All 11 primary and 8 of 9 secondary studies at low risk of bias on the Newcastle-Ottawa Scale (provisional, single-reviewer assessment). ᵇ Substantial heterogeneity: primary I² = 98% (95% CrI 96–99%); the predictive interval spans protection to harm. ᶜ Credible interval includes both meaningful benefit and harm. ᵈ No funnel-plot asymmetry (Egger’s test p = 0.78), though power to detect it is limited. ᵉ The no-antibiotic comparator answers a different question and is highly prone to confounding by indication.</p>
</div>
<div class="it">
<p>La certezza è stata valutata secondo l’approccio GRADE <span class="citation" data-cites="Guyatt2008GRADE">(<a href="#ref-Guyatt2008GRADE" role="doc-biblioref">Guyatt et al. 2008</a>)</span>. Poiché tutte le evidenze sono osservazionali, entrambi i confronti partono da una certezza <em>bassa</em>; ciascuno è stato declassato per inconsistenza e imprecisione serie, risultando in una certezza <strong>molto bassa</strong> per entrambe le domande.</p>
</div>
<div class="it">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
</colgroup>
<thead>
<tr class="header">
<th>Esito: ICD incidente</th>
<th>k</th>
<th>OR aggregato (ICr 95%)</th>
<th>Effetto assoluto illustrativo*</th>
<th>Rischio di bias</th>
<th>Inconsistenza</th>
<th>Indirettezza</th>
<th>Imprecisione</th>
<th>Bias di pubblicazione</th>
<th>Certezza</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tetracicline vs altri antibiotici</td>
<td>11</td>
<td>0.86 (0.60–1.23)</td>
<td>17 vs 20 per 1,000 (12–24)</td>
<td>Non serioᵃ</td>
<td>Serioᵇ</td>
<td>Non serio</td>
<td>Serioᶜ</td>
<td>Non rilevatoᵈ</td>
<td><strong>Molto bassa</strong></td>
</tr>
<tr class="even">
<td>Tetracicline vs nessun antibiotico</td>
<td>9</td>
<td>1.06 (0.75–1.53)</td>
<td>5 vs 5 per 1,000 (4–8)</td>
<td>Non serioᵃ</td>
<td>Serioᵇ</td>
<td>Serioᵉ</td>
<td>Serioᶜ</td>
<td>Non rilevatoᵈ</td>
<td><strong>Molto bassa</strong></td>
</tr>
</tbody>
</table>
<p>* Solo illustrativo: assume un rischio di base di 20 per 1.000 pazienti esposti ad antibiotici (contesto ospedaliero) e di 5 per 1.000 non esposti; gli effetti assoluti variano con il rischio di base. ᵃ Tutti gli 11 studi primari e 8 dei 9 secondari a basso rischio di bias secondo la scala Newcastle-Ottawa (valutazione provvisoria, singolo revisore). ᵇ Eterogeneità sostanziale: I² primario = 98% (95% CrI 96–99%); l’intervallo predittivo spazia dalla protezione al danno. ᶜ L’intervallo di credibilità include sia un beneficio sia un danno rilevanti. ᵈ Nessuna asimmetria del funnel plot (test di Egger p = 0.78), sebbene la potenza per rilevarla sia limitata. ᵉ Il comparatore senza antibiotico risponde a una domanda diversa ed è fortemente soggetto a confondimento per indicazione.</p>
</div>
</section>
<section id="interpretationinterpretazione" class="level2">
<h2><span class="en">Interpretation</span><span class="it">Interpretazione</span></h2>
<div class="en">
<p>Restricted to the protocol’s intended comparator (another antibiotic), the data provide <strong>suggestive but uncertain</strong> evidence that tetracycline exposure lowers CDI risk: the pooled OR is below 1 with a modest posterior probability of a meaningful reduction, but the credible interval still includes no effect and heterogeneity is substantial. A confidently protective conclusion emerges only under a strong literature-based prior. These findings distinguish a plausibly <em>lower associated risk</em> from established <em>protective therapy</em>.</p>
</div>
<div class="it">
<p>Limitandosi al comparatore previsto dal protocollo (un altro antibiotico), i dati forniscono un’evidenza <strong>suggestiva ma incerta</strong> che l’esposizione alle tetracicline riduca il rischio di ICD: l’OR aggregato è inferiore a 1 con una modesta probabilità a posteriori di una riduzione rilevante, ma l’intervallo di credibilità include ancora l’assenza di effetto e l’eterogeneità è sostanziale. Una conclusione decisamente protettiva emerge solo con un forte prior basato sulla letteratura. Questi risultati distinguono un plausibile <em>minor rischio associato</em> da una <em>terapia protettiva</em> consolidata.</p>
</div>
</section>
<section id="discussiondiscussione" class="level2">
<h2><span class="en">Discussion</span><span class="it">Discussione</span></h2>
<div class="en">
<p><strong>What these results mean.</strong> Restricted to the protocol comparator (another antibiotic), the pooled odds ratio is 0.86 (0.60–1.23), with roughly a 81% posterior probability of <em>any</em> protection but only 35% for a clinically meaningful effect (OR &lt; 0.80). The dominant feature is heterogeneity (τ = 0.55): the predictive interval for a new study spans OR 0.25–2.88, so a well-conducted future study could plausibly land anywhere from meaningful protection to modest harm. Against a <em>no-antibiotic</em> comparator the association is essentially null (1.06 (0.75–1.53)), and a confidently protective reading emerges only under a prior anchored on the older Tariq (2018) estimate — that is, it is driven by prior belief, not the new data. The doxycycline-restricted sensitivity analysis is the most encouraging signal (OR 0.78 (0.56–1.02), P(OR&lt;1) = 0.97), but its interval still touches 1.</p>
<p><strong>Is tetracycline preferable to macrolides or other agents to reduce CDI?</strong> Not on this evidence. First, no included study provides a head-to-head tetracycline-versus-macrolide comparison; the comparator is a heterogeneous mix of “other antibiotics”, so a macrolide-specific preference would be an extrapolation. Second, the pooled effect is uncertain (credible interval crossing 1, substantial heterogeneity). Third, the protective interpretation is fragile, depending on prior belief. The defensible statement is narrower: tetracyclines — particularly doxycycline — are biologically plausible lower-CDI-risk agents and are unlikely to be worse than typical comparators, with a <em>possible</em> modest advantage. That can reasonably inform stewardship <em>when the spectrum required is genuinely equivalent</em>, but it does not meet the bar for a formal recommendation to prefer them, and certainly not specifically over macrolides.</p>
<p><strong>Implications for future studies.</strong></p>
<ul>
<li>Use active-comparator, new-user cohort designs (or target-trial emulation) with an explicit, clinically matched comparator — e.g. doxycycline vs a macrolide for community-acquired pneumonia — rather than pooling against undifferentiated “other antibiotics”.</li>
<li>Reduce confounding by indication: adjust for or match on prior CDI, PPI use, hospitalisation, age and comorbidity; treat case-control evidence cautiously given its design-related divergence.</li>
<li>Standardise CDI ascertainment (testing protocols, exposure and outcome windows) so heterogeneity reflects biology rather than measurement.</li>
<li>Analyse by agent (doxycycline vs minocycline vs tigecycline) to isolate the doxycycline signal.</li>
<li>Pre-register and report completely to limit publication bias, and consider individual-participant-data meta-analysis to resolve the heterogeneity the predictive interval exposes.</li>
<li>Where clinically and ethically appropriate, a pragmatic randomised trial with CDI as a pre-specified secondary outcome would provide the confirmatory evidence observational data cannot.</li>
</ul>
</div>
<div class="it">
<p><strong>Cosa significano questi risultati.</strong> Limitandosi al comparatore del protocollo (un altro antibiotico), l’odds ratio aggregato è 0.86 (0.60–1.23), con circa il 81% di probabilità a posteriori di un <em>qualsiasi</em> effetto protettivo ma solo il 35% per un effetto clinicamente rilevante (OR &lt; 0,80). L’elemento dominante è l’eterogeneità (τ = 0.55): l’intervallo predittivo per un nuovo studio va da OR 0.25–2.88, quindi uno studio futuro ben condotto potrebbe collocarsi ovunque, da una protezione rilevante a un modesto danno. Rispetto a un comparatore <em>senza antibiotico</em> l’associazione è sostanzialmente nulla (1.06 (0.75–1.53)), e una lettura decisamente protettiva emerge solo con un prior ancorato alla stima precedente di Tariq (2018) — cioè è guidata dalla convinzione a priori, non dai nuovi dati. L’analisi di sensibilità limitata alla doxiciclina è il segnale più incoraggiante (OR 0.78 (0.56–1.02), P(OR&lt;1) = 0.97), ma il suo intervallo tocca ancora 1.</p>
<p><strong>Le tetracicline sono preferibili ai macrolidi o ad altri agenti per ridurre l’ICD?</strong> Non sulla base di queste evidenze. Primo, nessuno studio incluso fornisce un confronto diretto tetraciclina-vs-macrolide; il comparatore è un insieme eterogeneo di “altri antibiotici”, perciò una preferenza specifica sui macrolidi sarebbe un’estrapolazione. Secondo, l’effetto aggregato è incerto (intervallo di credibilità che attraversa 1, eterogeneità sostanziale). Terzo, l’interpretazione protettiva è fragile e dipende dalla convinzione a priori. L’affermazione difendibile è più circoscritta: le tetracicline — in particolare la doxiciclina — sono agenti biologicamente plausibili a minor rischio di ICD ed è improbabile che siano peggiori dei comparatori abituali, con un <em>possibile</em> modesto vantaggio. Ciò può ragionevolmente orientare la stewardship <em>quando lo spettro richiesto è realmente equivalente</em>, ma non raggiunge la soglia per una raccomandazione formale a preferirle, e certamente non specificamente rispetto ai macrolidi.</p>
<p><strong>Implicazioni per gli studi futuri.</strong></p>
<ul>
<li>Usare disegni di coorte active-comparator, new-user (o emulazione di target trial) con un comparatore esplicito e clinicamente confrontabile — es. doxiciclina vs un macrolide nella polmonite acquisita in comunità — invece di aggregare contro “altri antibiotici” indistinti.</li>
<li>Ridurre il confondimento da indicazione: aggiustare o appaiare per ICD pregressa, uso di IPP, ospedalizzazione, età e comorbidità; trattare con cautela le evidenze caso-controllo data la divergenza legata al disegno.</li>
<li>Standardizzare l’accertamento dell’ICD (protocolli di test, finestre di esposizione ed esito) affinché l’eterogeneità rifletta la biologia e non la misurazione.</li>
<li>Analizzare per agente (doxiciclina vs minociclina vs tigeciclina) per isolare il segnale della doxiciclina.</li>
<li>Pre-registrare e riportare in modo completo per limitare il publication bias, e valutare una meta-analisi su dati individuali dei partecipanti per risolvere l’eterogeneità che l’intervallo predittivo evidenzia.</li>
<li>Ove clinicamente ed eticamente appropriato, uno studio randomizzato pragmatico con l’ICD come esito secondario pre-specificato fornirebbe la conferma che i dati osservazionali non possono dare.</li>
</ul>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<div class="en">
<p><strong>Caveats.</strong> All included studies are observational; Newcastle-Ottawa scores are predominantly in the low-risk range, but the assessment is provisional pending duplicate full-text review. Estimates convert RR/HR to OR under a rare-outcome approximation. This is evidence synthesis for research and education, not treatment guidance for individual patients.</p>
</div>
<div class="it">
<p><strong>Avvertenze.</strong> Tutti gli studi inclusi sono osservazionali; i punteggi Newcastle-Ottawa sono prevalentemente nell’intervallo di basso rischio, ma la valutazione è provvisoria in attesa della doppia revisione del full-text. Le stime convertono RR/HR in OR con un’approssimazione per esiti rari. Si tratta di una sintesi delle evidenze a scopo di ricerca ed educativo, non di una guida terapeutica per il singolo paziente.</p>
</div>
</div>
</div>
</section>
<section id="referencesbibliografia" class="level2">
<h2><span class="en">References</span><span class="it">Bibliografia</span></h2>
<div class="en">
<p>Bibliographic entries for the studies in the synthesis are cited in Table 1 and listed below. Author and year are taken from the extraction; titles, journals and DOIs in <code>references.bib</code> are a scaffold to be verified/completed by the author (Tariq 2018 and a few studies whose DOIs came from the source files are complete).</p>
</div>
<div class="it">
<p>Le voci bibliografiche degli studi nella sintesi sono citate nella Tabella 1 ed elencate qui sotto. Autore e anno provengono dall’estrazione; titoli, riviste e DOI in <code>references.bib</code> sono uno scheletro da verificare/completare (Tariq 2018 e alcuni studi con DOI dai file sorgente sono completi).</p>
</div>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Adams2017" class="csl-entry" role="listitem">
Adams, Daniel J., Matthew D. Eberly, Michael Rajnik, and Cade M. Nylund. 2017. <span>“Risk Factors for Community-Associated <span class="nocase">Clostridium difficile</span> Infection in Children.”</span> <em>The Journal of Pediatrics</em> 186: 105–9. <a href="https://doi.org/10.1016/j.jpeds.2017.03.032">https://doi.org/10.1016/j.jpeds.2017.03.032</a>.
</div>
<div id="ref-Baxter2008" class="csl-entry" role="listitem">
Baxter, R., G. Ray, and B. Fireman. 2008. <span>“Case-Control Study of Antibiotic Use and Subsequent <span class="nocase">Clostridium difficile</span>–Associated Diarrhea in Hospitalized Patients.”</span> <em>Infection Control &amp; Hospital Epidemiology</em> 29 (1): 44–50. <a href="https://doi.org/10.1086/524320">https://doi.org/10.1086/524320</a>.
</div>
<div id="ref-Boven2026" class="csl-entry" role="listitem">
Boven, A., Harry Vranken, E. Vlieghe, et al. 2026. <span>“Commonly Prescribed Drugs as Risk Factors for <span class="nocase">Clostridioides difficile</span> Infections: A <span>Swedish</span> Population-Based Case–Control Study.”</span> <em>Gut</em>, ahead of print. <a href="https://doi.org/10.1136/gutjnl-2025-337629">https://doi.org/10.1136/gutjnl-2025-337629</a>.
</div>
<div id="ref-Brown2016" class="csl-entry" role="listitem">
Brown, Kevin A., Makoto M. Jones, N. Daneman, et al. 2016. <span>“Importation, Antibiotics, and <span class="nocase">Clostridium difficile</span> Infection in Veteran Long-Term Care: A Multilevel Case–Control Study.”</span> <em>Annals of Internal Medicine</em> 164 (12): 787–94. <a href="https://doi.org/10.7326/m15-1754">https://doi.org/10.7326/m15-1754</a>.
</div>
<div id="ref-Carmichael2023" class="csl-entry" role="listitem">
Carmichael, H., S. M. Asch, and E. Bendavid. 2023. <span>“<span class="nocase">Clostridium difficile</span> and Other Adverse Events from Overprescribed Antibiotics for Acute Upper Respiratory Infection.”</span> <em>Journal of Internal Medicine</em> 293 (4): 470–80. <a href="https://doi.org/10.1111/joim.13597">https://doi.org/10.1111/joim.13597</a>.
</div>
<div id="ref-Delaney2007" class="csl-entry" role="listitem">
Delaney, J. A. Chris, Sandra Dial, Alan Barkun, and Samy Suissa. 2007. <span>“Antimicrobial Drugs and Community-Acquired <span class="nocase">Clostridium difficile</span>-Associated Disease, <span>UK</span>.”</span> <em>Emerging Infectious Diseases</em> 13 (5): 761–63. <a href="https://doi.org/10.3201/eid1305.061124">https://doi.org/10.3201/eid1305.061124</a>.
</div>
<div id="ref-Dial2008" class="csl-entry" role="listitem">
Dial, S., A. Kezouh, A. Dascal, A. Barkun, and S. Suissa. 2008. <span>“Patterns of Antibiotic Use and Risk of Hospital Admission Because of <span class="nocase">Clostridium difficile</span> Infection.”</span> <em>CMAJ</em> 179 (8): 767–72. <a href="https://doi.org/10.1503/cmaj.071812">https://doi.org/10.1503/cmaj.071812</a>.
</div>
<div id="ref-Doernberg2012" class="csl-entry" role="listitem">
Doernberg, S., L. Winston, D. Deck, and H. Chambers. 2012. <span>“Does Doxycycline Protect Against Development of <span class="nocase">Clostridium difficile</span> Infection?”</span> <em>Clinical Infectious Diseases</em> 55 (5): 615–20. <a href="https://doi.org/10.1093/cid/cis457">https://doi.org/10.1093/cid/cis457</a>.
</div>
<div id="ref-Guh2015" class="csl-entry" role="listitem">
Guh, A., S. Adkins, Qunna Li, et al. 2017. <span>“Risk Factors for Community-Associated <span class="nocase">Clostridium difficile</span> Infection in Adults: A Case-Control Study.”</span> <em>Open Forum Infectious Diseases</em> 4 (4): ofx171. <a href="https://doi.org/10.1093/ofid/ofx171">https://doi.org/10.1093/ofid/ofx171</a>.
</div>
<div id="ref-Guyatt2008GRADE" class="csl-entry" role="listitem">
Guyatt, Gordon H., Andrew D. Oxman, Gunn E. Vist, et al. 2008. <span>“<span>GRADE</span>: An Emerging Consensus on Rating Quality of Evidence and Strength of Recommendations.”</span> <em>BMJ</em> 336 (7650): 924–26. <a href="https://doi.org/10.1136/bmj.39489.470347.AD">https://doi.org/10.1136/bmj.39489.470347.AD</a>.
</div>
<div id="ref-Kuntz2011" class="csl-entry" role="listitem">
Kuntz, Jennifer L., Elizabeth A. Chrischilles, Jane F. Pendergast, Loreen A. Herwaldt, and Philip M. Polgreen. 2011. <span>“Incidence of and Risk Factors for Community-Associated <span class="nocase">Clostridium difficile</span> Infection: A Nested Case-Control Study.”</span> <em>BMC Infectious Diseases</em> 11 (1): 194. <a href="https://doi.org/10.1186/1471-2334-11-194">https://doi.org/10.1186/1471-2334-11-194</a>.
</div>
<div id="ref-Miller2023" class="csl-entry" role="listitem">
Miller, A. C., A. Arakkal, Daniel K. Sewell, Alberto Maria Segre, Joseph Tholany, and P. Polgreen. 2023. <span>“Comparison of Different Antibiotics and the Risk for Community-Associated <span class="nocase">Clostridioides difficile</span> Infection: A Case–Control Study.”</span> <em>Open Forum Infectious Diseases</em> 10 (8): ofad413. <a href="https://doi.org/10.1093/ofid/ofad413">https://doi.org/10.1093/ofid/ofad413</a>.
</div>
<div id="ref-OLeary2023" class="csl-entry" role="listitem">
O’Leary, Ashley L., Arthur K. Chan, Bethany A. Wattengel, Jiachen Xu, and K. Mergenhagen. 2023. <span>“Impact of Doxycycline on <span class="nocase">Clostridioides difficile</span> Infection in Patients Hospitalized with Community-Acquired Pneumonia.”</span> <em>American Journal of Infection Control</em> 52 (3): 280–83. <a href="https://doi.org/10.1016/j.ajic.2023.09.007">https://doi.org/10.1016/j.ajic.2023.09.007</a>.
</div>
<div id="ref-Saito2025" class="csl-entry" role="listitem">
Saito, T., Y. Sato, and S. Yamamoto. 2025. <span>“Antimicrobial Combinations as Novel Indicators for <span class="nocase">Clostridioides difficile</span> Infection Development: Population-Based, Nested Case-Controlled Study in <span>Japan</span> — the <span>Shizuoka Kokuho</span> Database Study.”</span> <em>Journal of Infection and Chemotherapy</em> 31 (2): 102552. <a href="https://doi.org/10.1016/j.jiac.2024.11.002">https://doi.org/10.1016/j.jiac.2024.11.002</a>.
</div>
<div id="ref-Predrag2016" class="csl-entry" role="listitem">
Stojanović, Predrag. 2016. <span>“Analysis of Risk Factors and Clinical Manifestations Associated with <span class="nocase">Clostridium difficile</span> Disease in <span>Serbian</span> Hospitalized Patients.”</span> <em>Brazilian Journal of Microbiology</em> 47 (4): 902–10. <a href="https://doi.org/10.1016/j.bjm.2016.07.011">https://doi.org/10.1016/j.bjm.2016.07.011</a>.
</div>
<div id="ref-Strom2017" class="csl-entry" role="listitem">
Ström, J., J. Tham, F. Månsson, et al. 2017. <span>“The Association Between <span>GABA</span>-Modulators and <span class="nocase">Clostridium difficile</span> Infection — a Matched Retrospective Case-Control Study.”</span> <em>PLoS ONE</em> 12 (1): e0169386. <a href="https://doi.org/10.1371/journal.pone.0169386">https://doi.org/10.1371/journal.pone.0169386</a>.
</div>
<div id="ref-Tariq2018" class="csl-entry" role="listitem">
Tariq, Raseen, and Sahil Khanna. 2018. <span>“Low Risk of Primary <span class="nocase">Clostridium difficile</span> Infection with Tetracyclines: A Systematic Review and Meta-Analysis.”</span> <em>Clinical Infectious Diseases</em> 66 (4): 514–22. <a href="https://doi.org/10.1093/cid/cix833">https://doi.org/10.1093/cid/cix833</a>.
</div>
<div id="ref-Tartof2015" class="csl-entry" role="listitem">
Tartof, S., G. Rieg, R. Wei, H. Tseng, S. Jacobsen, and Kalvin C. Yu. 2015. <span>“A Comprehensive Assessment Across the Healthcare Continuum: Risk of Hospital-Associated <span class="nocase">Clostridium difficile</span> Infection Due to Outpatient and Inpatient Antibiotic Exposure.”</span> <em>Infection Control &amp; Hospital Epidemiology</em> 36 (12): 1409–16. <a href="https://doi.org/10.1017/ice.2015.220">https://doi.org/10.1017/ice.2015.220</a>.
</div>
<div id="ref-Tilton2019" class="csl-entry" role="listitem">
Tilton, C. S., and S. W. Johnson. 2019. <span>“Development of a Risk Prediction Model for Hospital-Onset <span class="nocase">Clostridium difficile</span> Infection in Patients Receiving Systemic Antibiotics.”</span> <em>American Journal of Infection Control</em> 47 (3): 280–84. <a href="https://doi.org/10.1016/j.ajic.2018.08.021">https://doi.org/10.1016/j.ajic.2018.08.021</a>.
</div>
<div id="ref-Watson2018" class="csl-entry" role="listitem">
Watson, T., J. Hickok, S. Fraker, K. Korwek, R. E. Poland, and E. Septimus. 2018. <span>“Evaluating the Risk Factors for Hospital-Onset <span class="nocase">Clostridium difficile</span> Infections in a Large Healthcare System.”</span> <em>Clinical Infectious Diseases</em> 66 (12): 1957–59. <a href="https://doi.org/10.1093/cid/cix1112">https://doi.org/10.1093/cid/cix1112</a>.
</div>
<div id="ref-Webb2020" class="csl-entry" role="listitem">
Webb, B., A. Subramanian, B. Lopansri, et al. 2020. <span>“Antibiotic Exposure and Risk for Hospital-Associated <span class="nocase">Clostridioides difficile</span> Infection.”</span> <em>Antimicrobial Agents and Chemotherapy</em> 64 (4): e02169–19. <a href="https://doi.org/10.1128/aac.02169-19">https://doi.org/10.1128/aac.02169-19</a>.
</div>
<div id="ref-WellsNOS" class="csl-entry" role="listitem">
Wells, George A., Beverley Shea, Dianne O’Connell, et al. 2011. <em>The <span>Newcastle-Ottawa Scale</span> (<span>NOS</span>) for Assessing the Quality of Nonrandomised Studies in Meta-Analyses</em>. <a href="http://www.ohri.ca/programs/clinical_epidemiology/oxford.asp" class="uri">Http://www.ohri.ca/programs/clinical_epidemiology/oxford.asp</a>.
</div>
<div id="ref-Yu2021" class="csl-entry" role="listitem">
Yu, H., N. Flaster, A. L. Casanello, and D. Curcio. 2021. <span>“Assessing Risk Factors, Mortality, and Healthcare Utilization Associated with <span class="nocase">Clostridioides difficile</span> Infection in Four <span>Latin American</span> Countries.”</span> <em>Brazilian Journal of Infectious Diseases</em> 25 (1): 101040. <a href="https://doi.org/10.1016/j.bjid.2020.11.005">https://doi.org/10.1016/j.bjid.2020.11.005</a>.
</div>
</div>
<hr />
<div class="cap">
<div class="en">
<p>Reproducible source: <code>report.qmd</code>. Bayesian normal-normal hierarchical model (<code>bayesmeta</code>, exact numerical posterior), confirmed by <code>brms</code>/Stan MCMC. Re-render with <code>quarto render report.qmd</code>.</p>
</div>
<div class="it">
<p>Sorgente riproducibile: <code>report.qmd</code>. Modello gerarchico normale-normale bayesiano (<code>bayesmeta</code>, posteriori numerica esatta), confermato con MCMC <code>brms</code>/Stan. Ri-generare con <code>quarto render report.qmd</code>.</p>
</div>
</div>
<div id="quarto-navigation-envelope" class="hidden">
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1zaWRlYmFyLXRpdGxl">Tetracyclines &amp; C. difficile</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXItdGl0bGU=">Tetracyclines &amp; C. difficile</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6SG9tZQ==">Home</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L2luZGV4Lmh0bWw=">/index.html</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6TWV0YS1hbmFseXNpcyByZXBvcnQ=">Meta-analysis report</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L3JlcG9ydC5odG1s">/report.html</span></p>
<div class="hidden quarto-markdown-envelope-contents" data-render-id="Zm9vdGVyLWxlZnQ=">
<p>Bayesian meta-analysis · thesis-stage evidence synthesis</p>
</div>
</div>
<div id="quarto-meta-markdown" class="hidden">
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW1ldGF0aXRsZQ==">Tetracyclines and the risk of <em>Clostridioides difficile</em> infection – Tetracyclines &amp; C. difficile</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLXR3aXR0ZXJjYXJkdGl0bGU=">Tetracyclines and the risk of <em>Clostridioides difficile</em> infection – Tetracyclines &amp; C. difficile</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW9nY2FyZHRpdGxl">Tetracyclines and the risk of <em>Clostridioides difficile</em> infection – Tetracyclines &amp; C. difficile</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW1ldGFzaXRlbmFtZQ==">Tetracyclines &amp; C. difficile</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLXR3aXR0ZXJjYXJkZGVzYw==">Updated systematic review &amp; Bayesian random-effects meta-analysis</span></p>
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW9nY2FyZGRkZXNj">Updated systematic review &amp; Bayesian random-effects meta-analysis</span></p>
</div>
</section>

</main> <!-- /main -->
<script id = "quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <div class='footer-contents'>Bayesian meta-analysis · thesis-stage evidence synthesis</div>  
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>

</body>

</html>
